import { NextResponse } from "next/server";
import { getActiveStore } from "@/lib/store/active-store";

/**
 * The Slack app manifest, built from what this deployment actually expects.
 *
 * Slack can create an app from a manifest, which matters because the alternative
 * is typing seven scopes, three URLs and two event subscriptions into a web form
 * and discovering a typo later, when the assistant answers in Teams but silently
 * not in Slack. Every value here is derived from the same constants the running
 * code uses, so the app cannot be configured to something the code does not do.
 *
 * Unlike the Teams package this is a ONE-TIME artefact for us, not something a
 * client ever touches: Slack distribution works the other way round — we publish
 * one app and each workspace installs it with the "Add to Slack" link.
 *
 * Owner-only, and it carries no secret: the signing secret and client secret are
 * generated by Slack after the app exists.
 */
export const dynamic = "force-dynamic";

/** Must stay in step with SLACK_SCOPES in app/(app)/link/slack-actions.ts — the
 *  install link requests exactly these, and Slack refuses an install asking for a
 *  scope the app was not configured with. */
const BOT_SCOPES = [
  "chat:write", // reply, and post approvals
  "users:read", // who is speaking
  "users:read.email", // their address: the key everything else joins on
  "app_mentions:read", // being @mentioned in a channel
  "im:history", // read the direct message that was just sent
  "im:read",
  "im:write", // open a DM to reach somebody
];

export async function GET() {
  const ctx = await getActiveStore();
  if (!ctx?.active) return new NextResponse("Not signed in", { status: 401 });
  if (!(ctx.active.role === "owner" || ctx.isPlatformAdmin)) {
    return new NextResponse("Owners only", { status: 403 });
  }

  const fnBase = (process.env.NEXT_PUBLIC_SUPABASE_URL ?? "").replace(/\/$/, "");
  if (!fnBase) {
    return NextResponse.json({ error: "Supabase URL isn't set." }, { status: 503 });
  }
  const events = `${fnBase}/functions/v1/slack-events`;
  const interactions = `${fnBase}/functions/v1/slack-interactions`;
  const oauth = `${fnBase}/functions/v1/slack-oauth`;

  const manifest = {
    display_information: {
      name: "The Assistant",
      description: "Answers from your own material, and acts in your own systems.",
      background_color: "#e05a2b",
      long_description:
        "Ask it a question and it answers from your organisation's own documents and policies. " +
        "Ask it to do something and it acts in the systems you have connected, with anything " +
        "consequential held for a named person to approve. When it cannot answer, it reaches a " +
        "colleague and brings their answer back to you.",
    },
    features: {
      bot_user: { display_name: "The Assistant", always_online: true },
      app_home: { home_tab_enabled: false, messages_tab_enabled: true, messages_tab_read_only_enabled: false },
    },
    oauth_config: {
      redirect_urls: [oauth],
      scopes: { bot: BOT_SCOPES },
    },
    settings: {
      event_subscriptions: {
        request_url: events,
        // message.im is the direct message; app_mention is being called on in a
        // channel. Deliberately not subscribing to all channel messages: the
        // assistant should answer when addressed, not read everything said.
        bot_events: ["message.im", "app_mention"],
      },
      // Approve and Decline on a held action post back here.
      interactivity: { is_enabled: true, request_url: interactions },
      org_deploy_enabled: false,
      socket_mode_enabled: false,
      token_rotation_enabled: false,
    },
  };

  return new NextResponse(JSON.stringify(manifest, null, 2), {
    headers: {
      "content-type": "application/json",
      "content-disposition": 'attachment; filename="slack-app-manifest.json"',
      "cache-control": "no-store",
    },
  });
}
